services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: containers
    environment:
      TUNNEL_TOKEN: # cloudflared tunnel token 26d72e15-8b31-4b37-8e7a-d2e3b3ad5cba
      LOGLEVEL: debug
    restart: unless-stopped
    networks:
      - wg-network

  fastapi:
    build:
      context: .
      dockerfile: services.Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8080"
    volumes:
      - ./services:/app
    environment:
      UVICORN_LOG_LEVEL: debug
    restart: unless-stopped
    networks:
      - wg-network

networks:
  wg-network:
    driver: bridge