services:
# cloudflared tunnel token 26d72e15-8b31-4b37-8e7a-d2e3b3ad5cba
# cloudflared tunnel run --token
  fastapi:
    build:
      context: .
      dockerfile: services.Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8080"
    volumes:
      - ./services:/app
      - ./.git:/.git
    environment:
      UVICORN_LOG_LEVEL: debug
    restart: unless-stopped
    networks:
      - wg-network

networks:
  wg-network:
    driver: bridge